services:
  db:
    image: postgres:15
    container_name: star-burger-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: star-burger-backend
    volumes:
      - .:/star-burger
      - static_data:/star-burger/staticfiles
      - media_data:/star-burger/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "until pg_isready -h db -p 5432; do echo 'Waiting for database...'; sleep 2; done &&
            python manage.py migrate &&
            python manage.py loaddata data.json &&
            python manage.py collectstatic --noinput &&
            gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: star-burger-frontend
    volumes:
      - ./bundles:/star-burger/bundles
      - /star-burger/node_modules
    ports:
      - "1234:1234"
    environment:
      - ENVIRONMENT=dev
    command: npx parcel watch bundles-src/index.js --port 1234 --dist-dir bundles --public-url="./"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: star-burger-nginx
    ports:
      - "80:80"
    volumes:
      - static_data:/usr/share/nginx/html/static
      - media_data:/usr/share/nginx/html/media
      - ./bundles:/usr/share/nginx/html/bundles
    depends_on:
      - backend
      - frontend

volumes:
  static_data:
  media_data:
  postgres_data:

