# Generated by Django 3.2.15 on 2025-06-03 10:52

from django.db import migrations


def fill_order_item_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.all().iterator(chunk_size=200):
        item.price = item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_order_item_prices),
    ]
