# Generated by Django 3.2.15 on 2025-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('assembly', 'Сборка'), ('delivery', 'Доставка'), ('completed', 'Выполнен')], default='accepted', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
