services:
  db:
    image: postgres:15
    container_name: star-burger-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: star-burger-backend
    restart: always
    volumes:
      - ./staticfiles:/star-burger/backend/staticfiles
      - ./media:/star-burger/backend/media
      - ./frontend/bundles:/star-burger/frontend/bundles
    env_file:
      - .env
    command: >
      sh -c "until pg_isready -h db -p 5432; do echo 'Waiting for database...'; sleep 2; done &&
            python manage.py migrate &&
            python manage.py loaddata data.json &&
            python manage.py collectstatic --noinput &&
            gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    working_dir: /star-burger/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: star-burger-frontend
    restart: "no"
    command: sh -c "npx parcel build frontend/bundles-src/index.js --dist-dir frontend/bundles --public-url='./'"
    environment:
      - ENVIRONMENT=prod
    volumes:
      - ./frontend/bundles:/star-burger/frontend/bundles

volumes:
  postgres_data: