# Generated by Django 3.2.15 on 2025-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20250530_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
